"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { ShoppingBag, X, Printer, Copy, Check } from "lucide-react"

interface Ingredient {
  name: string
  amount?: string
}

interface ShoppingListGeneratorProps {
  ingredients: Ingredient[]
  title: string
}

export default function ShoppingListGenerator({ ingredients, title }: ShoppingListGeneratorProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    const text = `Shopping List for ${title}:\n\n${ingredients
      .map((ing) => `• ${ing.amount || ""} ${ing.name}`)
      .join("\n")}`
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handlePrint = () => {
    const printWindow = window.open("", "_blank")
    if (!printWindow) return

    const html = `
      <html>
        <head>
          <title>Shopping List - ${title}</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              line-height: 1.6;
              max-width: 800px;
              margin: 0 auto;
              padding: 20px;
            }
            h1 {
              color: #2e7d32;
              border-bottom: 2px solid #2e7d32;
              padding-bottom: 10px;
            }
            ul {
              padding-left: 20px;
            }
            li {
              margin-bottom: 8px;
            }
            .footer {
              margin-top: 30px;
              font-size: 12px;
              color: #666;
              text-align: center;
              border-top: 1px solid #eee;
              padding-top: 10px;
            }
          </style>
        </head>
        <body>
          <h1>Shopping List for ${title}</h1>
          <ul>
            ${ingredients.map((ing) => `<li>${ing.amount || ""} ${ing.name}</li>`).join("")}
          </ul>
          <div class="footer">
            Generated by ChefGPT - Happy Cooking!
          </div>
          <script>
            window.onload = function() {
              window.print();
            }
          </script>
        </body>
      </html>
    `
    printWindow.document.open()
    printWindow.document.write(html)
    printWindow.document.close()
  }

  return (
    <>
      <Button
        onClick={() => setIsOpen(true)}
        className="flex items-center gap-2 bg-gradient-to-r from-primary to-accent hover:from-primary/90 hover:to-accent/90 text-white transition-all duration-200 shadow-md hover:shadow-lg"
      >
        <ShoppingBag className="h-4 w-4" />
        <span>Generate Shopping List</span>
      </Button>

      {isOpen && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 backdrop-blur-sm">
          <div
            className="bg-white rounded-lg shadow-xl w-full max-w-md max-h-[90vh] flex flex-col overflow-hidden"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="bg-gradient-to-r from-primary to-accent p-4 text-white flex justify-between items-center">
              <h3 className="text-xl font-bold flex items-center">
                <ShoppingBag className="h-5 w-5 mr-2" />
                Shopping List
              </h3>
              <button
                onClick={() => setIsOpen(false)}
                className="text-white hover:bg-white/20 rounded-full p-1 transition-colors"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <div className="p-4 overflow-y-auto flex-grow">
              <h4 className="font-medium text-lg mb-2">{title}</h4>
              <ul className="space-y-2 mb-4">
                {ingredients.map((ing, index) => (
                  <li key={index} className="flex items-start gap-2 p-2 hover:bg-gray-50 rounded-md transition-colors">
                    <div className="h-5 w-5 rounded-full border border-primary/50 flex-shrink-0 mt-0.5"></div>
                    <span>
                      {ing.amount && <span className="font-medium">{ing.amount}</span>} {ing.name}
                    </span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="border-t p-4 flex gap-2 bg-gray-50">
              <Button
                onClick={handlePrint}
                variant="outline"
                className="flex-1 flex items-center justify-center gap-2 border-primary/30 hover:bg-primary/5"
              >
                <Printer className="h-4 w-4" />
                <span>Print</span>
              </Button>
              <Button
                onClick={handleCopy}
                variant="outline"
                className="flex-1 flex items-center justify-center gap-2 border-primary/30 hover:bg-primary/5"
              >
                {copied ? (
                  <>
                    <Check className="h-4 w-4" />
                    <span>Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="h-4 w-4" />
                    <span>Copy</span>
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
